packages:
  - "packages/*"
  - "packages/config/*"
allowBuilds:
  "@swc/core": true
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@turbo/darwin-64@2.11.1"
  - "@turbo/darwin-arm64@2.11.1"
  - "@turbo/linux-64@2.11.1"
  - "@turbo/linux-arm64@2.11.1"
  - "@turbo/windows-64@2.11.1"
  - "@turbo/windows-arm64@2.11.1"
  - turbo@2.11.1
