name: "✨ Format"

on:
  pull_request:
    branches: [main, dev]
    paths-ignore:
      - "**/*.md"
      - ".vscode/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: "Verifies Prettier formatting across all files"
    if: "!startsWith(github.head_ref, 'sync/')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-env

      - name: Check Format
        run: pnpm run format:check
