name: "🛡️ Type Check"

on:
  push:
    branches: [main, dev]
    paths-ignore:
      - "**/*.md"
      - ".vscode/**"
  pull_request:
    branches: [main, dev]
    paths-ignore:
      - "**/*.md"
      - ".vscode/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typecheck:
    name: "Performs static TypeScript analysis on all packages and apps"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-env

      - name: Run Type Check
        run: pnpm run type-check
